vich_uploader:
    db_driver: orm

    mappings:
       map_image:
           uri_prefix: /images/map
           upload_destination: '%kernel.project_dir%/public/images/map'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
